version: '3'

services:
  redishost:
    image: "redis:latest"
    container_name: redishost
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  frontendhost:
    image: "frontend:latest"  # Replace with the actual image for your frontend application
    container_name: frontendhost
    ports:
      - "5000:5000"
    depends_on:
      - redishost
    command: ["python", "frontend.py"]

  backendhost:
    image: "backend:latest"  # Replace with the actual image for your backend application
    container_name: backendhost
    ports:
      - "5001:5001"
    depends_on:
      - redishost
    command: ["python", "backend.py"]

